### PR TITLE
chore: bump components

### PR DESCRIPTION
**Pull request by billypchan**
bump for components

### CODE REVIEW

**Review by johnxnguyen — APPROVED** [review]

**Comment by johnxnguyen** [comment]
@billypchan if it's just a component bump and all tests pass, then you don't need any approving reviews.

**Comment by billypchan** [comment]
@zenkins release major

**Comment by billypchan** [comment]
@zenkins release major

**Comment by billypchan** [comment]
@zenkins release major

**Comment by billypchan** [comment]
@zenkins release major

**Review by David-Henner — APPROVED** [review]

**Comment by billypchan** [comment]
@zenkins release major

**Pull request merged**
